jaguarete_store/carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar', views.add, name='add'),
    path('eliminar', views.remove, name="remove")
]

jaguarete_store/jaguarete_store/urls.py
from django.contrib import admin

from django.urls import path
from django.urls import include

from django.conf.urls.static import static
from django.conf import settings

from . import views

from products.views import ProductListView

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    #path('categories/<int:categoria_id>',views.producto_categoria,name="categoria"),
    path('acerca_de/', views.acerca_de, name='acerca_de'),
    path('usuarios/login', views.login_view, name='login'),
    path('usuarios/logout', views.logout_view, name='logout'),
    path('usuarios/registro', views.register, name='register'),
    path('admin/', admin.site.urls),
    path('nuevo-producto/', views.newproducts, name='newproducts'),
    path('productos/', include('products.urls')), #products/:id
    path('categorias/', include('categories.urls')),
    path('carrito/', include('carts.urls')),
    path('orden/', include('orders.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jaguarete_store/templates/acerca_de.html
{% extends 'base.html' %}

{% block content %}
    
    <div class="col">
        <h2 class="text mt-4">ACERCA DE NOSOTROS</h2>
        
        <br>
        <p class="text mt-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis laboriosam ipsum placeat voluptatem quidem fugiat minus fuga vitae atque magnam enim labore quas, error quia officia nulla, iste, cumque dolores!</p>
        
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Odit itaque aliquid perspiciatis maxime architecto magnam voluptas doloribus delectus distinctio reprehenderit id, accusantium incidunt temporibus repudiandae laudantium mollitia, modi quia inventore!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere nulla quae eum omnis, illo maiores labore vitae suscipit provident deleniti quos doloremque sit, laudantium velit libero iusto? Culpa, et quae! </p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Non animi dolore necessitatibus ab. Quod ullam eveniet accusamus optio dolorum qui reiciendis ut harum, molestias explicabo esse praesentium provident ex magni. </p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis labore ipsa, ratione enim eum tenetur quasi eius deserunt magni quia fugiat id, alias asperiores, saepe dolores nobis architecto repudiandae eaque. </p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio consequatur voluptatem ipsa blanditiis impedit deserunt, corporis amet temporibus itaque, porro nulla architecto. Placeat aut modi unde totam animi nihil perspiciatis!</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Doloremque ipsam alias, aliquid error repudiandae in a repellendus voluptatum praesentium adipisci exercitationem vero sint numquam fugit aperiam quod iste ab fugiat?</p>
        
    </div>

{% endblock %}

jaguarete_store/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Tienda</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        
    </head>
    <body style="height: 100%;">

        {% include 'brand.html' %}
        {% include 'navbar.html' %}

        <div class="container">
            
            {% include 'messages.html' %}

            <div class="row mt-4">

                {% block content %}
                {% endblock %}

            </div>
        </div>
        <div class="display box mt-5">
            <p style="color: white;">s</p>
        </div>
        <div class="display box mt-5">
            <p style="color: white;">l</p>
        </div>
        <div class="display box mt-5">
            <p style="color: white;">t</p>
        </div>
        <div class="display box mt-5">
            <p style="color: white;">u</p>
        </div>
        <div class="display box mt-5">
            <p style="color: white;">u</p>
        </div>
        <div class="display box mt-1">
            <p style="color: white;">u</p>
        </div>
        
        <footer class="footer py-3 bg-dark">
            {% include 'footer.html' %}            
        </footer>

    </body>

    <script src="https://kit.fontawesome.com/7efd9e34c5.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
</html>

jaguarete_store/templates/brand.html
{% url 'login' as login %}
{% url 'register' as register %}
{% url 'carts:cart' as cart %}

<nav class="navbar navbar-expand-md bg-white navbar-white">
    <a href="{% url 'index' %}" class="navbar-brand text-weight-bold">Jaguarete Store</a>

    <button type="button" name="button" class="navbar-toggler navbar-toggler-right" data-toggle="collapse" data-target="#navb">
        <span class="navbar-toggler-icon"></span>
    </button>
    
    <div id="navb" class="navbar-collapse collapse hide">

        <ul class="nav navbar-nav ml-auto ">

            <li class="nav-item {% if request.path == cart %}active{% endif %}">
                <a href="{{ cart }}" class="btn btn-primary">
                    Mi carrito <span class="fas fa-shopping-cart"></span>
                </a>
            </li>

            {% if user.is_authenticated %}
                <li class="navbar-item">
                    <a href="{% url 'logout' %}" class="btn btn-primary ml-2">
                        <span class="fas fa-sign-in-alt"></span>
                        Logout</a>
                </li>
            {% else %}
                <li class="navbar-item {% if request.path == login %}active{% endif %}">
                    <a href="{{ login }}" class="btn btn-primary ml-2">
                        <span class="fas fa-user"></span>
                        Login</a>
                </li>

                <li class="navbar-item {% if request.path == register %}active{% endif %}">
                    <a href="{{ register }}" class="btn btn-primary ml-2">
                        <span class="fas fa-user-plus"></span>
                        Registro</a>
                </li>
            {% endif %}

        </ul>

    </div>

</nav>

jaguarete_store/templates/footer.html
<div class="container mt-2" >
  <span style="color: lightgray;">© Copyright 2021 Jaguarete Kaa SA, todos los derechos reservados. </span>
    <span class="m-auto" style="color: lightgray;">Designed by Luciano Morán Martin</span>
</div>

jaguarete_store/templates/index.html
{% extends 'base.html' %}

{% block content %}
    
    <div class="col">
        <h4 class="text-center"> {{ message }} </h4>
        
        
        {% include 'products/snippets/list.html' %}
        
    </div>

{% endblock %}

jaguarete_store/templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert {% if message.tags == 'success' %}alert-success{% else %}alert-danger{% endif %}">                      
            <button type="button" class="close" data-dismiss="alert">x</button>
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

jaguarete_store/templates/navbar.html
<!-- {% url 'login' as login %}
{% url 'register' as register %}
{% url 'carts:cart' as cart %} -->
{% url 'index' as index %}
{% url 'categories:categoria' as categorias %}

<nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <ul class="nav navbar-nav">
        <li class="nav-item" {% if request.path == index %}active{% endif %}>
          <a class="nav-link" href="{% url 'index' %}">HOME</a>
        </li>

        {% include 'Categories/categoria.html'%}
        

        <li class="nav-item" {% if request.path == cart %}active{% endif %}>
          <a class="nav-link" href="{% url 'acerca_de' %}">ACERCA DE...</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="mailto:jaguareteKaa@gmail.com">CONTACTO</a>
        </li>

        {% if user.is_superuser %}
            <li class="navbar-item">
                <a href="{% url 'newproducts' %}" class="nav-link text-weight-bold">NUEVO PRODUCTO</a>
            </li>
        {% endif %}

    </ul>
    <ul class="nav navbar-nav ml-auto ">
        {% include 'products/snippets/search.html' %}
    </ul>


    <!-- <button type="button" name="button" class="navbar-toggler navbar-toggler-right" data-toggle="collapse" data-target="#navb">
        <span class="navbar-toggler-icon"></span>
    </button>
    
    <div id="navb" class="navbar-collapse collapse hide">

        <ul class="navbar-nav">
            <li class="nav-item {% if request.path == cart %}active{% endif %}">
                <a class="nav-link" href="{{ cart }}">
                    Mi carrito <span class="fas fa-shopping-cart"></span>
                </a>
            </li>

        </ul>

        <ul class="nav navbar-nav ml-auto">

            {% if user.is_authenticated %}
                <li class="navbar-item">
                    <a href="{% url 'logout' %}" class="nav-link">
                        <span class="fas fa-sign-in-alt"></span>
                        Logout</a>
                </li>
            {% else %}
                <li class="navbar-item {% if request.path == login %}active{% endif %}">
                    <a href="{{ login }}" class="nav-link">
                        <span class="fas fa-user"></span>
                        Login</a>
                </li>

                <li class="navbar-item {% if request.path == register %}active{% endif %}">
                    <a href="{{ register }}" class="nav-link">
                        <span class="fas fa-user-plus"></span>
                        Registro</a>
                </li>
            {% endif %}

        </ul>

    </div> -->

</nav>

jaguarete_store/templates/newproducts.html
{% extends 'base.html' %}

{% block content %}

    <div class="col">

        <h1 class="text-center"><strong>NUEVO PRODUCTO</strong></h1><br>

        <!-- Formulario -->
        <div class="row">
            <div class="col">
             
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
               
                    {{ form.title }}
                                  
                    <!-- Categorias:{{ form.categoria }} -->
                  
                    {{ form.image }}
                  
                    {{ form.description }}
                                      
                    Precio: ${{ form.price }}
                  
                    <button type="submit" class="btn btn-primary btn-block">Cargar</button>
                </form>
            </div>
        </div>

    </div>
{% endblock %}

jaguarete_store/templates/nuevo_producto.html
{% extends 'base.html' %}

{% block content %}
    <div class="container py-5">
        {% if messages %}
            {% for message in messages %}

                <div class="alert {% if message.tags == 'error'%}alert-danger{% else %}alert-success{% endif %} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>   
            {% endfor %}
        {% endif %}
    
        <h1 style="text-align: center;"><strong>NUEVO PRODUCTO</strong></h1><br>
        <div class="row">
            <div class="col">
             
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
               
                    {{ form.titulo }}
                                  
                    Categorias:{{ form.categoria }}
                  
                    {{ form.imagen }}
                  
                    {{ form.descripcion }}
                                      
                    Precio: ${{ form.precio }}
                  
                    <button type="submit" class="btn btn-primary btn-block">Cargar</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}
    