jaguarete_store/carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar', views.add, name='add'),
    path('eliminar', views.remove, name="remove")
]

jaguarete_store/jaguarete_store/urls.py
from django.contrib import admin

from django.urls import path
from django.urls import include

from django.conf.urls.static import static
from django.conf import settings

from . import views

from products.views import ProductListView

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    #path('categories/<int:categoria_id>',views.producto_categoria,name="categoria"),
    path('acerca_de/', views.acerca_de, name='acerca_de'),
    path('usuarios/login', views.login_view, name='login'),
    path('usuarios/logout', views.logout_view, name='logout'),
    path('usuarios/registro', views.register, name='register'),
    path('admin/', admin.site.urls),
    path('nuevo-producto/', views.newproducts, name='newproducts'),
    path('productos/', include('products.urls')), #products/:id
    path('categorias/', include('categories.urls')),
    path('carrito/', include('carts.urls')),
    path('orden/', include('orders.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jaguarete_store/products/urls.py
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    path('search', views.ProductSearchListView.as_view(), name='search'),
    path('<slug:slug>', views.ProductDetailView.as_view(), name='product'), #id -> llave primaria
    
]

jaguarete_store/products/models.py
import uuid

from django.db import models
from django.utils.text import slugify
from django.db.models.signals import pre_save

#from categories.models import Category

class Product(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0.0)
    slug = models.SlugField(null=False, blank=False, unique=True)
    image = models.ImageField(upload_to='products/', null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    #category = models.ManyToManyField(Category, blank=True)

    # def save(self, *args, **kwargs):
    #     self.slug = slugify(self.title)
    #     super(Product, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

def set_slug(sender, instance, *args, **kwargs): #callback
    if instance.title and not instance.slug:
        slug = slugify(instance.title)

        while Product.objects.filter(slug=slug).exists():
            slug = slugify(
                '{}-{}'.format(instance.title, str(uuid.uuid4())[:8] )
            )

        instance.slug = slug
    

pre_save.connect(set_slug, sender=Product)

jaguarete_store/products/views.py
from django.shortcuts import render

from django.db.models import Q

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from .models import Product

class ProductListView(ListView):
    template_name = 'index.html'
    queryset = Product.objects.all().order_by('-id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['message'] = 'Listado de productos'
        
        return context

class ProductDetailView(DetailView): #id -> pk
    model = Product
    template_name = 'products/product.html'

class ProductSearchListView(ListView):
    template_name = 'products/search.html'

    def get_queryset(self):
        filters = Q(title__icontains=self.query()) | Q(category__title__icontains=self.query())
        return Product.objects.filter(filters)

    def query(self):
        return self.request.GET.get('q')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.query()
        context['count'] = context['product_list'].count()

        return context

jaguarete_store/products/templates/products/snippets/list.html
<div class="row">
    {% for object in product_list %}
        {% if forloop.counter < 4 %}
            <div class="col-4 mt-5">
                {% include 'products/snippets/product.html' with product=object %}
            </div>

        {% elif forloop.counter == 4 %}
            <br>
            <h3 class="mt-5"><ins>Más productos</ins></h3>
            
                {% include 'products/snippets/product_others.html' with product=object %}

        {% else %}

                {% include 'products/snippets/product_others.html' with product=object %}

          
        {% endif %}
        
    {% endfor %}
</div>

jaguarete_store/products/templates/products/snippets/product.html
<!-- Product hasta 3 -->
<div class="card h-100 ">

    {% if product.image %}
        <img src="{{ product.image.url }}" alt="Imagen del producto" height="300" >
    {% endif %}

    <div class="card-body">
        <h5 class="card-title">{{ product.title }}</h5>
        <p class="card-text">{{ product.description }}</p>
        <a href="{% url 'products:product' product.slug %}" class="btn btn-primary">Ver más</a>
    </div>
</div>

jaguarete_store/products/templates/products/snippets/product_others.html
<a href="{% url 'products:product' product.slug %}" class="list-group-item list-group-item-action mt-3 mb-3">
    <img src="{{ product.image.url }}" width="100px">&nbsp;
    <strong>{{ product.title }}</strong><br>
    {{ product.description }}
  </a><br>

jaguarete_store/products/templates/products/snippets/search.html
<form action="{% url 'products:search' %}">
    <div class="input-group">
        <input type="text" name="q" value="{{ query }}" class="form-control" palceholder="Buscar">
        <div class="input-group-append">
            <input type="submit" name="" value="Buscar" class="btn btn-primary">
        </div>
    </div>

</form>