jaguarete_store/carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar', views.add, name='add'),
    path('eliminar', views.remove, name="remove")
]

jaguarete_store/jaguarete_store/urls.py
from django.contrib import admin

from django.urls import path
from django.urls import include

from django.conf.urls.static import static
from django.conf import settings

from . import views

from products.views import ProductListView

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    #path('categories/<int:categoria_id>',views.producto_categoria,name="categoria"),
    path('acerca_de/', views.acerca_de, name='acerca_de'),
    path('usuarios/login', views.login_view, name='login'),
    path('usuarios/logout', views.logout_view, name='logout'),
    path('usuarios/registro', views.register, name='register'),
    path('admin/', admin.site.urls),
    path('nuevo-producto/', views.newproducts, name='newproducts'),
    path('productos/', include('products.urls')), #products/:id
    path('categorias/', include('categories.urls')),
    path('carrito/', include('carts.urls')),
    path('orden/', include('orders.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jaguarete_store/carts/models.py
import uuid
import decimal

from django.db import models

from users.models import User
from products.models import Product

from django.db.models.signals import pre_save
from django.db.models.signals import post_save
from django.db.models.signals import m2m_changed

class Cart(models.Model):
    cart_id = models.CharField(max_length=100, null=False, blank=False, unique=True)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE) #Uno a muchos
    products = models.ManyToManyField(Product, through='CartProducts') #Muchos a muchos
    subtotal = models.DecimalField(default=0.0, max_digits=8, decimal_places=2)
    total = models.DecimalField(default=0.0, max_digits=8, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)

    FEE = 0.05 # 0.5%

    def __str__(self):
        return self.cart_id

    def update_totals(self):
        self.update_subtotal()
        self.update_total()

    def update_subtotal(self):
        self.subtotal = sum([
            cp.quantity * cp.product.price for cp in self.products_related()
        ])
        self.save()

    def update_total(self):
        self.total = self.subtotal + (self.subtotal * decimal.Decimal(Cart.FEE))
        self.save()

    def products_related(self):
        return self.cartproducts_set.select_related('product')

class CartProductsManager(models.Manager):

    def create_or_update_quantity(self, cart, product, quantity=1):
        object, created = self.get_or_create(cart=cart, product=product)

        if not created:
            quantity = object.quantity + quantity

        object.update_quantity(quantity)

        return object

class CartProducts(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)

    objects = CartProductsManager()

    def update_quantity(self, quantity=1):
        self.quantity = quantity
        self.save()

def set_cart_id(sender, instance, *args, **kwargs):
    if not instance.cart_id:
        instance.cart_id = str(uuid.uuid4())

def update_totals(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        instance.update_totals()

def post_save_update_totals(sender, instance, *args, **kwargs):
    instance.cart.update_totals()

pre_save.connect(set_cart_id, sender=Cart)
post_save.connect(post_save_update_totals, sender=CartProducts)
m2m_changed.connect(update_totals, sender=Cart.products.through)

jaguarete_store/carts/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404

from .models import CartProducts
from products.models import Product
from .utils import get_or_create_cart

def cart(request):
    cart = get_or_create_cart(request)

    return render(request, 'carts/cart.html', {
        'cart': cart
    })

def add(request):
    cart = get_or_create_cart(request)
    product = get_object_or_404(Product, pk=request.POST.get('product_id'))
    quantity = int(request.POST.get('quantity', 1))

    # cart.products.add(product, through_defaults={
    #     'quantity': quantity
    # })

    cart_product = CartProducts.objects.create_or_update_quantity(cart=cart, product=product, quantity=quantity)

    return render(request, 'carts/add.html', {
        'quantity': quantity,
        'cart_product': cart_product,
        'product': product
    })

def remove(request):
    cart = get_or_create_cart(request)
    product = get_object_or_404(Product, pk=request.POST.get('product_id'))


    cart.products.remove(product)

    return redirect('carts:cart')

jaguarete_store/carts/templates/carts/snippets/add.html
<form action="{% url 'carts:add' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="product_id" value="{{ product.id }}">
    
    <div class="">
        <button type="button" class="btn btn-info d-inline" id="remove">-</button>
        <input type="number" value="1" class="form-control col-sm-1 d-inline" id="quantity" name="quantity" readonly>
        <button type="button" class="btn btn-info" id="add">+</button>
    </div>

    <div class="mt-2">
        <button type="submit" class="btn btn-warning">Agregar al carrito</button>
    </div>
</form>

<script>
    const add = document.getElementById('add')
    const remove = document.getElementById('remove')
    const quantity = document.getElementById('quantity')

    add.addEventListener('click', function(){
        quantity.value = parseInt(quantity.value) + 1
    })

    remove.addEventListener('click', function(){
        value = parseInt(quantity.value)
        
        if(value != 1){
            value = value - 1
        }
        quantity.value = value
    })


</script>

jaguarete_store/carts/templates/carts/snippets/remove.html
<form action="{% url 'carts:remove' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="product_id" value="{{ product.id }}">
    <button type="submit" class="btn btn-link text-danger" style="padding:0px">Eliminar</button>
</form>